### PR TITLE
Replicate fig1

### PR DESCRIPTION
**Pull request by Shunsuke-Hori**
It is a little dirty, but it is successfully replicating figure 1.

Once v.0.7 is released, I'll make more updates and simplification

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @Shunsuke-Hori, this looks like a good start.

Do you plan to leave it all in the notebook or split it up into notebook and text files?  

If you're going to keep it in the notebook, I recommend dropping docstrings and instead embedding the documentation in the notebook, in separate cells where the Latex renders nicely.

Is there a way to get the numbers to display in nice tables?

When you have edited and are happy with the notebook, could you please put a copy [here](http://notes.quantecon.org/)?

**Comment by Shunsuke-Hori** [comment]
@jstac 
> Do you plan to leave it all in the notebook or split it up into notebook and text files?

From the coding perspective, it should be split. We'll get each result by a combo of medium size estimations (e.g. least square with restriction, VAR estimation with missing values) which mainly consist of a couple of small estimations (e.g. OLS, PCA), with a little changes/replacements depending on cases. There are going to be many reusable functions.

On the other hand, I think the noteworthy algorithms are in the "medium size estimations". Nicely rendered math would help to explain them. I'm wondering if it's possible to call functions defined in another notebook.

> Is there a way to get the numbers to display in nice tables?

I'll think about that. 

> When you have edited and are happy with the notebook, could you please put a copy here?

Of course.

-----

Sidenote: The main reason why I'm stopping here is the built-in support of `missing` in v.0.7. The treatment of missing value is one of the key points of the paper.

**Comment by Shunsuke-Hori** [comment]
Let me merge it at this stage. It's a good stopping point.

I hope the functions in `.jl` files are enough reusable.

**Some issues I'll post later.**
- documentation for functions in `.jl` files. 
- observable factor is not allowed. 
- restriction on factor loading (`lambda`) is not allowed.
- variance decomposition and IRF (cf `dynamic_factor_irf_vdecomp.m`) is missing
- table 1,3,4,5
- section 7
- read data is slightly off from the original one. because of the definition of median? i.e. median of `[1,2]` is `1.5` (which `median()` gives) or `1` (which authors are using)? 
- outputs of tables are not enough beautiful. need to find or wait for a better package?
- need support for `missing` by plotting packages. I'm avoiding `missing` now in plots

**Comment by jstac** [comment]
@Shunsuke-Hori Sounds good.  

When you think this is ready, please coordinate with Natasha regarding a QuantEcon blog post or news item announcing it and introducing the functionality.

Regards, John.

**Comment by jstac** [comment]
Please merge when ready.

**Pull request merged**
